### ISSUE TITLE
LaTeX is not getting rendered since update 3.0.0.10 -> 3.1.1.1 on Arch Linux

### ISSUE THREAD

**Issue by grmbrspp** [retext-project/pymarkups#12]
Hey! :) 
Since the last update my embedded LaTeX-Code is not getting rendered in ReText. Downgrading the package solves the problem. I have a local mathjax installation (version 3.1.4-1) but even if I uninstall it, the behavior does not change. I tried to delete my '.config/ReText project' folder and the ReTextrc file but that did not help either. Maybe a bug or am I doing something wrong?

**Comment by mitya57** [comment]
Hi!

Are you using Markdown or reStructuredText?

Can you open “Edit → View HTML code” (in ReText) and paste here two fragments from there:
- The `<script>` tag that includes MathJax.
- Any of the math fragments (which can be `<div>` or `<script>`).

Also can you make sure that “Edit → Use WebEngine (WebKit) renderer” is enabled?

**Comment by grmbrspp** [comment]
I'm using Markdown. 
In the HTML code there is no ```<script>``` and no ```<div>``` tag. It looks like that:
```
<!doctype html>
<html>
<head>
<meta http-equiv="content-type" content="text/html; charset=utf-8">
<meta name="generator" content="ReText 7.2.1">
<title>ex4</title>
</head>
<body>
...
</body>
</html>
```

Here's a place with LaTeX fragments:
```
<p>$m^n$ <br>
$n^4 = 16$</p>
```

WebKit renderer is enabled.
The ReTextrc file contains something like that:
```
[KFileDialog Settings]
Recent Files[$e]=***.pdf
Recent URLs[$e]=file:$HOME/***
detailViewIconSize=16
```

**Comment by mitya57** [comment]
Thank you for your answers!

I see you are using a single dollar delimiter. This delimiter is [disabled by default](https://pymarkups.readthedocs.io/en/latest/standard_markups.html#f1). Can you try adding the following line on top of your Markdown file?

```html
<!-- Required extensions: mdx_math(enable_dollar_delimiter=1) -->
```

Or, if you already have such a line or a `markdown-extensions.txt` file, does it have anything related to math?

Also I have just discovered that WebKit renderer is too old to support MathJax 3 :facepalm:. If you install Arch Linux' [mathjax2](https://archlinux.org/packages/community/any/mathjax2/) package then it should finally work.

**Comment by grmbrspp** [comment]
Ok, thank you, I got it working with the mathjax2 package installed and the line above my .md file (I did not need the line on version 3.0.0.10, I think).

I also had to uninstall the mathjax package. Without any mathjax installed, ReText seems to fall back on an online version of mathjax3, which also does not work. Will you fix this in your code? Otherwise I would ask the package maintainer to add mathjax2 as a dependency.

Thanks for your support! :)

**Comment by mitya57** [comment]
I think I will fix it by removing the WebKit backend in the next release, leaving only the WebEngine one…

Right now we have four different configurations, because we support WebKit and WebEngine backends, and MathJax v2 and v3. As this bug shows, one of these four configurations is not working.

**Comment by grmbrspp** [comment]
Ok, thank you! :)
