### ISSUE TITLE
Fail to load extensions due to broken logic

### ISSUE THREAD

**Issue by foxB612** [retext-project/pymarkups#16]
For [this piece of code](https://github.com/retext-project/pymarkups/blob/master/markups/markdown.py#L118-L126) which is used to load extensions: if `yaml` is not installed (which is the case on my computer), the code will enter the `else` block and skip the rest choices, resulting no extensions loaded even if a valid txt config file exists.

**Comment by mitya57** [comment]
Fixed! I wonder why no one else had noticed that.

Can you please confirm that the fix is working fine for you? If yes then I will make a new release soon.

**Comment by foxB612** [comment]
Thanks for the quick response! The fix works well for me.

**Comment by mitya57** [comment]
I released version 3.1.3 yesterday, which has this fix.

**Comment by foxB612** [comment]
> I released version 3.1.3 yesterday, which has this fix.

Updated and confirmed it works.
