### ISSUE TITLE
Implement Fountain markup

### ISSUE THREAD

**Issue by IBPX** [retext-project/pymarkups#3]
[Fountain](https://fountain.io/) is a lightweight markup format similar to Markdown, but for screenplays. Would it be possible to implement it here, so you can edit Fountain in ReText?

The full syntax is available [here](https://fountain.io/syntax).

**Comment by mitya57** [comment]
Hi @IBPX! I will be open to accepting a pull request to implement it, but I have absolutely no time to do it myself.

**Comment by mitya57** [comment]
PyMarkups supports [custom markups](https://pymarkups.readthedocs.io/en/latest/custom_markups.html) for a while now, so if someone wants to add a new markup they should use this mechanism.

Therefore I am closing this issue.
