### ISSUE TITLE
Bug: ReText not uses offline MathJax files from Arch Linux package

### ISSUE THREAD

**Issue by ali-hardan** [retext-project/pymarkups#4]
I have installed ReText on Arch Linux and I have installed `mathjax` package; but ReText still uses online MathJax.

That's because ReText try to find MathJax in `/usr/share/javascript/mathjax`, but Arch Linux will be install it to `/usr/share/mathjax`.

If I download MathJax from their github and put it to `/usr/share/javascript/mathjax`, ReText will use it.

**Comment by mitya57** [comment]
Thanks for the bug report! I am transferring it to PyMarkups as that’s where the code for MathJax integration lives.

**Comment by mitya57** [comment]
Fixed, this will be in the next PyMarkups release.
