### ISSUE TITLE
How to package the retext-project source code

### ISSUE THREAD

**Issue by zhangchunlu** [retext-project/pymarkups#6]
Thank you for your reply.May I ask which tool you use to package the source code of the retext-project? Because every time you use the retext tool, you have to install the relevant python environment, which is very troublesome

**Comment by mitya57** [comment]
Not sure if I understand your question. I am using standard Python tools: setuptools for building, pip for installing, twine for uploading releases.

As [documented](https://github.com/retext-project/retext/wiki/Installing-ReText#for-users-of-windows-and-macos) in the wiki, there will be no special installers for Windows as I do not use that OS.
