### ISSUE TITLE
How do I package the retext-project source code to generate executable files

### ISSUE THREAD

**Issue by zhangchunlu** [retext-project/pymarkups#7]
I mean how to generate the executable directly.For example, exe files in the Windows operating system, so I can be independent of the python environment

**Comment by mitya57** [comment]
This is in no way different than any other Python project.

You can read the instruction at https://github.com/retext-project/ReTextPortable although it is a bit outdated (e.g. the mentioned PyQt5 version is too old).

**Comment by mitya57** [comment]
Also there are some (unofficial!) binaries at https://portableapps.com/node/56132.
