### ISSUE TITLE
Unknown license type

### ISSUE THREAD

**Issue by tieugene** [retext-project/pymarkups#9]
MIT?
BSD?
It is important for packaging for main distros

**Comment by mitya57** [comment]
It is BSD, see https://github.com/retext-project/pymarkups/blob/master/LICENSE.

**Comment by mitya57** [comment]
The license is also specified in the metadata:
https://github.com/retext-project/pymarkups/blob/91d1e916f025bd5e3f2b15ace49c546c4ff6e170/setup.cfg#L9

and in trove classifiers:
https://github.com/retext-project/pymarkups/blob/91d1e916f025bd5e3f2b15ace49c546c4ff6e170/setup.cfg#L12

So I am closing this issue.
